### ISSUE TITLE
Disable Sprite Limit Option seems broken

### ISSUE THREAD

**Issue by aorin1** [libretro/Genesis-Plus-GX-Wide#17]
It's easily identifiable in Sonic the Hedgehog, as the sprite is misplaced in the intro, the option doesn't seem to be working, the non wide core variant is behaving as it should.

**Comment by vladikcomper** [comment]
It's not the emulator, it's actually the game to blame.

Sonic 1 abuses sprite limit in its Title screen by placing 20 garbage tiles off-screen to intentionally hit sprite limit and accurately cut off bottom of the Sonic's sprite so it won't be drawn on top of the "SONIC" text.

The only difference is that Widescreen core overdraws tiles and sprites, so you can actually see those garbage sprites, which would otherwise be off-screen in 4:3 aspect ratio.

**Comment by aorin1** [comment]
Interesting, I had no clue it was the case.
